config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, numericality: {only_integers: true}, inclusion: { in: (0..5) }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end

  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def destroy
      @review = Review.find(params[:id])
      @review.destroy
      redirect_to restaurant_path(@review.restaurant)
    end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :address %>
    <%= f.text_field :adress %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit a Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Index of Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to "#{restaurant.name} - Address: #{restaurant.address}", restaurant_path(restaurant)  %>
    </li>
  <% end %>
</ul>

<p>
  <%= link_to 'Add Restaurant', new_restaurant_path %>
</p>

app/views/restaurants/new.html.erb
<h1>Create a new Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Info about Restaurant</h1>

<p>Name: <%= @restaurant.name %></p>
<p>Address: <%= @restaurant.address %></p>

<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
  <% end %>
</ul>


<!-- Não use tag a no rails, sempre use link_to -->
<!-- <a href="/restaurants">All Restaurants</a> -->

<p>
  <%= link_to 'All Restaurants', restaurants_path %>
</p>

<p>
  <%= link_to 'Edit this Restaurant', edit_restaurant_path(@restaurant) %>
</p>

<p>
  <%= link_to 'Remove this Restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you Sure?' } %>
</p>

<p>
  <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
</p>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>